version: "3.8"

services:
  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.load_balancer
    ports:
      - "5000:5000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=Server

