version: "3.9"
services:
  load-balancer:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
    depends_on:
      - server
  server:
    build: .
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production
    volumes:
      - .:/app
