# Use Python base image
FROM python:3.8-slim

# Set working directory in the container
WORKDIR /app

# Copy requirements and app code
COPY requirements.txt .
COPY LoadBalancer.py .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that the load balancer runs on
EXPOSE 5000

# Command to run the load balancer
CMD ["python", "LoadBalancer.py"]
